{
 "title": "AirLux dashboard",
 "time": { "from": "2023-02-02T11:31:57.000Z", "to": "2023-02-03T12:45:05.000Z" },
 "panels": [
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "AirLuxDB",
     "rawSql": "SELECT * FROM AirLuxDB.rooms LIMIT 50 "
    }
   ]
  },
  {
   "title": "Captors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "AirLuxDB",
     "rawSql": "SELECT * FROM AirLuxDB.captors LIMIT 50 "
    }
   ]
  },
  {
   "title": "Captor temperatures over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "AirLuxDB",
     "rawSql": "SELECT value AS \"temperature\", created_at AS \"time\", captor_id AS \"ID\" FROM AirLuxDB.captor_values ORDER BY created_at LIMIT 500 "
    }
   ]
  }
 ]
}