FROM node:18

RUN mkdir -p /home/syncapi
WORKDIR /home/syncapi/

# Bundle app source
COPY /syncapi/. .


RUN npm install --silent \
  && npm update \
#  && npx tsc --init \
  && npx tsc


EXPOSE 6001

CMD [ "node", "/home/syncapi/build/index.js" ]