FROM redis

# Installation mysql,  et extensions
RUN apt-get update && apt-get install -y redis-server --option=Dpkg::Options::=--force-confdef \
    && apt-get install -y ufw \
    && apt-get install -y redis-tools \
    && apt-get install -y redis-server

WORKDIR /home

#COPY /redis/redis.conf /etc/redis/redis.conf

COPY /redis/set_up_redis.sh /home/set_up_redis.sh

COPY /redis/start_pubsub.sh /home/start_pubsub.sh

RUN chmod u+x set_up_redis.sh \
    && chmod u+x start_pubsub.sh

RUN ["/bin/bash", "/home/set_up_redis.sh"]

CMD ["/bin/bash", "/home/start_pubsub.sh"]