FROM node:18


COPY /localapp/package*.json ./

RUN mkdir -p /home/localapp
WORKDIR /home/localapp/

RUN npm install --silent

# Bundle app source
COPY /localapp/. .

#EXPOSE 8080

CMD [ "node", "mqtt/sub.js" ]