FROM ubuntu:18.04


# Variables d'environnement

# Installation mysql,  et extensions
RUN apt-get update \
&& apt-get install -y mysql-server \
&& apt-get install -y wget \
&& wget https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb \
&& apt-get install -y lsb-release \
&& apt-get install -y gnupg \
&& dpkg -i mysql-apt-config_0.8.24-1_all.deb \
&& apt-get update \
&& apt-get install -y mysql-shell \
&& apt-get install coreutils \
&& apt-get -qq -y install curl

WORKDIR /root

COPY /mysql/set_up_db.sh /root/set_up_db.sh

RUN chmod u+x set_up_db.sh

# Run necessary services
RUN ["/bin/bash", "/root/set_up_db.sh"]

WORKDIR /home
COPY /mysql/start_db.sh /home/start_db.sh
RUN chmod u+x start_db.sh
ENTRYPOINT ["/bin/bash", "/home/start_db.sh"]