FROM node:18

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY /pulseur/package*.json ./

RUN mkdir -p /home/pulseur
WORKDIR /home/pulseur/

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY /pulseur/. .

EXPOSE 7071

CMD ["node", "index.js"];
VOLUME /project/logs