FROM node:18

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY /pubsubjs/package*.json ./

RUN apt-get update -qq && apt-get install -y gcc make build-essential
RUN mkdir -p /home/websocketjs
WORKDIR /home/websocketjs/

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY /websocketjs/. .

EXPOSE 7071

#CMD ["node", "index.js"];
VOLUME /project/logs