
FROM php:7.4.1-apache

# Arguments defined in docker-compose.yml (not really bruh)
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

RUN printf "\n \n" | pecl install redis && docker-php-ext-enable redis
# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u 1000 -d /home/user user
RUN mkdir -p /home/user/.composer \ 
    && chown -R user:user /home/user

WORKDIR /var/www/sync-api
COPY syncapi/ /var/www/
COPY syncapi/.env.example /var/www/.env

COPY syncapi/set_up_api.sh /root/set_up_api.sh
COPY syncapi/vhost.conf /etc/apache2/sites-available/000-default.conf
WORKDIR /root
# Run necessary services
RUN chmod u+x set_up_api.sh \
    && chown -R www-data:www-data /var/www \
    && a2enmod rewrite
RUN ["/bin/bash", "/root/set_up_api.sh"]

#USER user
#COPY /sync-api/ /var/www/sync-api/

    
# Set working directory
#WORKDIR /root
